In [1]:
# contoh sederhana
import numpy as np

def convolve(image, kernel):
    """
    Melakukan operasi konvolusi pada citra dengan kernel tertentu.
    """
    img_h, img_w = image.shape
    k_h, k_w = kernel.shape
    pad_h, pad_w = k_h // 2, k_w // 2

    # Menambahkan padding ke citra
    padded_image = np.pad(image, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant', constant_values=0)

    # Hasil konvolusi
    output = np.zeros((img_h, img_w))

    # Melakukan operasi konvolusi
    for i in range(img_h):
        for j in range(img_w):
            region = padded_image[i:i+k_h, j:j+k_w]
            output[i, j] = np.sum(region * kernel)

    return output

# Contoh citra grayscale sederhana (5x5)
image = np.array([[10, 20, 30, 40, 50],
                  [60, 70, 80, 90, 100],
                  [110, 120, 130, 140, 150],
                  [160, 170, 180, 190, 200],
                  [210, 220, 230, 240, 250]])

# Kernel perataan 5x5
kernel = np.ones((5, 5)) / 25

# Melakukan konvolusi
result = convolve(image, kernel)
print("Hasil konvolusi:")
print(result)


Hasil konvolusi:
[[ 25.2  36.   48.   40.8  32.4]
 [ 45.6  64.   84.   70.4  55.2]
 [ 72.  100.  130.  108.   84. ]
 [ 69.6  96.  124.  102.4  79.2]
 [ 61.2  84.  108.   88.8  68.4]]


In [2]:
#contoh menggunakan gambar hitam putih
import numpy as np
from PIL import Image

def convolve(image, kernel):
    """
    Melakukan operasi konvolusi pada citra dengan kernel tertentu.
    """
    img_h, img_w = image.shape
    k_h, k_w = kernel.shape
    pad_h, pad_w = k_h // 2, k_w // 2

    # Menambahkan padding ke citra
    padded_image = np.pad(image, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant', constant_values=0)

    # Hasil konvolusi
    output = np.zeros((img_h, img_w))

    # Melakukan operasi konvolusi
    for i in range(img_h):
        for j in range(img_w):
            region = padded_image[i:i+k_h, j:j+k_w]
            output[i, j] = np.sum(region * kernel)

    return output

# Membaca citra Unand.jpeg dan mengonversi ke grayscale
image_path = "Unand.jpeg"
image = Image.open(image_path).convert("L")
image = np.array(image, dtype=np.float32)

# Kernel perataan 5x5
kernel = np.ones((5, 5)) / 25

# Melakukan konvolusi
result = convolve(image, kernel)
print("Hasil konvolusi berhasil diproses.")

# Simpan hasil citra setelah konvolusi
result_image = Image.fromarray(result.astype(np.uint8))
result_image.save("Unand_convolved.jpeg")

Hasil konvolusi berhasil diproses.


In [3]:
#contoh menggunakan gambar tanpa mengubah warna
import numpy as np
from PIL import Image

def convolve(image, kernel):
    """
    Melakukan operasi konvolusi pada citra dengan kernel tertentu.
    """
    img_h, img_w, channels = image.shape
    k_h, k_w = kernel.shape
    pad_h, pad_w = k_h // 2, k_w // 2

    # Menambahkan padding ke citra
    padded_image = np.pad(image, ((pad_h, pad_h), (pad_w, pad_w), (0, 0)), mode='constant', constant_values=0)

    # Hasil konvolusi
    output = np.zeros((img_h, img_w, channels))

    # Melakukan operasi konvolusi pada setiap channel
    for c in range(channels):
        for i in range(img_h):
            for j in range(img_w):
                region = padded_image[i:i+k_h, j:j+k_w, c]
                output[i, j, c] = np.sum(region * kernel)

    return np.clip(output, 0, 255)  # Pastikan hasil tetap dalam rentang warna RGB

# Membaca citra Unand.jpeg tanpa mengubah warna
image_path = "Unand.jpeg"
image = Image.open(image_path)
image = np.array(image, dtype=np.float32)

# Kernel perataan 5x5
kernel = np.ones((5, 5)) / 25

# Melakukan konvolusi pada citra berwarna
result = convolve(image, kernel)
print("Hasil konvolusi berhasil diproses.")

# Simpan hasil citra setelah konvolusi tanpa mengubah warna
result_image = Image.fromarray(result.astype(np.uint8))
result_image.save("Unand_convolved.jpeg")


Hasil konvolusi berhasil diproses.
